--------------------------------------------------------------------------------
-- tables/TEXT_MESSAGE
--------------------------------------------------------------------------------
CREATE TABLE GAME
(
	ID					INTEGER NOT NULL, --SERIAL 			NOT NULL,
	HOME_ID             INTEGER NOT NULL,
	HOME_NAME			VARCHAR(100)	NOT NULL,
	AWAY_ID             INTEGER NOT NULL,
	AWAY_NAME			VARCHAR(100)	NOT NULL,
	GAME_DATE           TIMESTAMP WITH TIME ZONE NOT NULL,
	STATUS              VARCHAR(100)	NOT NULL,
	MATCH_DAY           INTEGER NOT NULL,
    GOALS_HOME          INTEGER NOT NULL,
    GOALS_AWAY          INTEGER NOT NULL,
	CONSTRAINT GAME_PK PRIMARY KEY ( ID )
);


CREATE TABLE ODD
(
	ID					SERIAL 			NOT NULL,
	GAME_ID             INTEGER NOT NULL,
	ODDS_HOME             REAL NOT NULL,
	ODDS_AWAY             REAL NOT NULL,
	ODDS_TIE              REAL NOT NULL,
	ODDS_OVER             REAL NOT NULL,
	ODDS_UNDER            REAL NOT NULL,
	CONSTRAINT ODD_PK PRIMARY KEY ( ID )
);

ALTER TABLE ODD ADD CONSTRAINT ODD_U01 UNIQUE ( GAME_ID );
ALTER TABLE ODD ADD CONSTRAINT ODD_FK01 FOREIGN KEY ( GAME_ID ) REFERENCES GAME ( ID );


CREATE TABLE ALLOWED_USERS
(
	ID					SERIAL 			NOT NULL,
	NAME              VARCHAR(1000)	NOT NULL,
	USERNAME              VARCHAR(100)	NOT NULL,
	EMAIL              VARCHAR(1000)	NOT NULL,
	PASSWORD              VARCHAR(100)	NOT NULL,
	ROLE              VARCHAR(100)	NOT NULL,
	OPT_OUT             BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT ALLOWED_USERS_PK PRIMARY KEY ( ID )
);
ALTER TABLE ALLOWED_USERS ADD CONSTRAINT ALLOWED_USERS_U01 UNIQUE ( NAME );
ALTER TABLE ALLOWED_USERS ADD CONSTRAINT ALLOWED_USERS_U02 UNIQUE ( USERNAME );
ALTER TABLE ALLOWED_USERS ADD CONSTRAINT ALLOWED_USERS_U03 UNIQUE ( EMAIL );

INSERT INTO bet.allowed_users(
            id, name, username, email, password, role)
    VALUES (nextval('bet.allowed_users_id_seq'), 'ELZ2xseYxiOqV19jtOkIAhC2dsbHmMYjqldfY7TpCAIQtnbGx5jGI6pXX2O06QgCELZ2xseYxiOqV19jtOkIAhC2dsbHmMYjqldfY7TpCAIQtnbGx5jGI6pXX2O06QgCELZ2xseYxiOqV19jtOkIAgbWiqn1u/PTuZFxgihvcjM=',
     'XXX', 'ELZ2xseYxiOqV19jtOkIAhC2dsbHmMYjqldfY7TpCAIQtnbGx5jGI6pXX2O06QgCELZ2xseYxiOqV19jtOkIAhC2dsbHmMYjqldfY7TpCAIQtnbGx5jGI6pXX2O06QgCELZ2xseYxiOqV19jtOkIAtotaH5p7u01d1R605o615U=', 'rG2Gp860hjYuxFf+XIwvHw==', 'ADMIN');


CREATE TABLE BET
(
	ID					SERIAL 			NOT NULL,
	GAME_ID             INTEGER NOT NULL,
	USER_ID             INTEGER NOT NULL,
	RESULT_BET          VARCHAR(100)	NOT NULL,
	RESULT_POINTS       INTEGER	NOT NULL DEFAULT 0,
	OVER_BET            VARCHAR(100),
	OVER_POINTS         INTEGER	NOT NULL DEFAULT 0,
	BET_DATE           TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT BET_PK PRIMARY KEY ( ID )
);
ALTER TABLE BET ADD CONSTRAINT BET_FK01 FOREIGN KEY ( GAME_ID ) REFERENCES GAME ( ID );
ALTER TABLE BET ADD CONSTRAINT BET_FK02 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );
ALTER TABLE BET ADD CONSTRAINT BET_U01 UNIQUE ( GAME_ID, USER_ID );



CREATE TABLE ENCRYPTED_BET
(
	ID					SERIAL 			NOT NULL,
	GAME_ID             INTEGER NOT NULL,
	USER_ID             INTEGER NOT NULL,
	RESULT_BET          VARCHAR(1000)	NOT NULL,
	OVER_BET            VARCHAR(1000),
	BET_DATE           TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT ENCRYPTED_BET_PK PRIMARY KEY ( ID )
);
ALTER TABLE ENCRYPTED_BET ADD CONSTRAINT ENCRYPTED_BET_FK01 FOREIGN KEY ( GAME_ID ) REFERENCES GAME ( ID );
ALTER TABLE ENCRYPTED_BET ADD CONSTRAINT ENCRYPTED_BET_FK02 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );
ALTER TABLE ENCRYPTED_BET ADD CONSTRAINT ENCRYPTED_BET_U01 UNIQUE ( GAME_ID, USER_ID );



CREATE TABLE RSS_FEED
(
	ID					SERIAL 			NOT NULL,
	TITLE             VARCHAR(1000),
	LINK             VARCHAR(1000),
	IMAGE             VARCHAR(1000),
	PUBLISH_DATE           TIMESTAMP WITHOUT TIME ZONE,
	CONSTRAINT RSS_FEED_PK PRIMARY KEY ( ID )
);


CREATE TABLE COMMENTS
(
	ID					SERIAL 			NOT NULL,
	COMMENT             VARCHAR(1000),
	USER_ID             INTEGER NOT NULL,
	COMMENT_DATE           TIMESTAMP WITH TIME ZONE,
	CONSTRAINT COMMENTS_PK PRIMARY KEY ( ID )
);

ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );

CREATE TABLE FRIEND
(
	ID					SERIAL 			NOT NULL,
	USER_ID             INTEGER NOT NULL,
	FRIEND_ID             INTEGER NOT NULL,
	CONSTRAINT FRIEND_PK PRIMARY KEY ( ID )
);

ALTER TABLE FRIEND ADD CONSTRAINT FRIENDS_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );
ALTER TABLE FRIEND ADD CONSTRAINT FRIENDS_FK02 FOREIGN KEY ( FRIEND_ID ) REFERENCES ALLOWED_USERS ( ID );
ALTER TABLE FRIEND ADD CONSTRAINT FRIENDS_U01 UNIQUE ( USER_ID, FRIEND_ID );


CREATE TABLE RANK_HISTORY
(
	ID					SERIAL 			NOT NULL,
	RANK                INTEGER,
	POINTS                INTEGER,
	USER_ID             INTEGER NOT NULL,
	RANK_DATE           TIMESTAMP WITH TIME ZONE,
	CONSTRAINT RANK_HISTORY_PK PRIMARY KEY ( ID )
);

ALTER TABLE RANK_HISTORY ADD CONSTRAINT RANK_HISTORY_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );


CREATE TABLE USER_STREAK
(
	ID					SERIAL 			NOT NULL,
	STREAK              INTEGER,
	USER_ID             INTEGER NOT NULL,
	CONSTRAINT USER_STREAK_PK PRIMARY KEY ( ID )
);

ALTER TABLE USER_STREAK ADD CONSTRAINT USER_STREAK_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );

CREATE TABLE USER_STREAK_HISTORY
(
	ID					SERIAL 			NOT NULL,
	MAX_STREAK              INTEGER,
	MIN_STREAK              INTEGER,
	USER_ID             INTEGER NOT NULL,
	CONSTRAINT USER_STREAK_HISTORY_PK PRIMARY KEY ( ID )
);

ALTER TABLE USER_STREAK_HISTORY ADD CONSTRAINT USER_STREAK_HISTORY_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );

