

CREATE TABLE COMMENT_LIKE
(
	ID					SERIAL 			NOT NULL,
	COMMENT_ID             INTEGER NOT NULL,
	USER_ID             INTEGER NOT NULL,
	CONSTRAINT COMMENT_LIKE_PK PRIMARY KEY ( ID )
);

ALTER TABLE COMMENT_LIKE ADD CONSTRAINT COMMENT_LIKE_FK01 FOREIGN KEY ( USER_ID ) REFERENCES ALLOWED_USERS ( ID );
ALTER TABLE COMMENT_LIKE ADD CONSTRAINT COMMENT_LIKE_FK02 FOREIGN KEY ( COMMENT_ID ) REFERENCES COMMENTS ( ID );
ALTER TABLE COMMENT_LIKE ADD CONSTRAINT COMMENT_LIKE_U01 UNIQUE ( USER_ID, COMMENT_ID );
