
CREATE TABLE DEADLINES
(
	ID					SERIAL 			NOT NULL,
	DATE_FROM           TIMESTAMP WITH TIME ZONE NOT NULL,
	DATE_TO           TIMESTAMP WITH TIME ZONE NOT NULL,
    CURRENT_MATCH_DAYS VARCHAR(100),
    ALLOWED_MATCH_DAYS VARCHAR(100),
    BET_DEADLINE_TEXT VARCHAR(1000),
	CONSTRAINT DEADLINES_PK PRIMARY KEY ( ID )
);